eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 5000
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq: 
    host: localhost
    port: 5672
  zipkin:
    rabbitmq:
      queue: zipkin

zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service